version: '3.7'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - 3306:3306
    container_name: mysql
volumes:
  mysql:
    driver: local
